name: Dataswap build & Test
on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ROOT_Address: ""
      Filecoin_Contract_Address: ""
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        npm install
    - name: Build
      run: |
        npm run build

  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: deploy localnet
      run: |
        docker run -d -p 1234:1234  --name localnet siriusyim/lotus-devnet:0.3.0
        sleep 30
        docker exec localnet /usr/local/bin/lotus wallet list
    - name: Install dependencies
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        NETWORK: ${{ secrets.NETWORK_NAME }}
        LOCALNET_RPC_URL: ${{ secrets.LOCALNET_RPC_URL }}
        CALIBRATION_RPC_URL: ${{secrets.CALIBRATION_RPC_URL}}
        FILECOIN_MAINNET_RPC_URL: ${{secrets.FILECOIN_MAINNET_RPC_URL}}
        DEPLOYER_ADDRESS: ${{ secrets.DEPLOYER_ADDRESS }}
      run: |
        npm install --save-dev hardhat
        npm install --save-dev ts-node
        git clone https://github.com/dataswap/core.git
        cd core && yarn install && yarn hardhat compile
        npx hardhat deploy --network $NETWORK
    - name: Create Datcap pool
      run: |
        export Root_Address=$(docker exec localnet lotus msig inspect f080 |grep t0100 |awk '{print $2}') 
        export Filecoin_Contract_Address=$(npx hardhat getProxyAddress --type localnet --name Filecoin)
        echo "ROOT_Address : $Root_Address"
        echo "Filecoin_Contract_Address : $Filecoin_Contract_Address"
        docker exec localnet lotus-shed verifreg add-verifier $Root_Address $Filecoin_Contract_Address 10000000
        docker exec localnet lotus filplus list-notaries

    - name: Test
      env:
        PRIVATE_KEY_BIDDER: ${{secrets.PRIVATE_KEY_BIDDER}}
        PRIVATE_KEY_DATASETAUDITOR: ${{secrets.PRIVATE_KEY_DATASETAUDITOR}}
        PRIVATE_KEY_METADATASUBMITTER: ${{secrets.PRIVATE_KEY_METADATASUBMITTER}}
        PRIVATE_KEY_PROOFSUBMITTER: ${{secrets.PRIVATE_KEY_PROOFSUBMITTER}}
      run: |
        echo "ok!"
