name: Dataswap build & Test
on:
    workflow_dispatch:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/*.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
                      ${{ runner.os }}-
            - name: Install dependencies
              run: |
                  npm install
            - name: Build
              run: |
                  npm run build
            - name: Build Test
              run: |
                  npm run build:test

    Test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: deploy localnet
              run: |
                  docker run -d -p 1234:1234  --name localnet dataswap/lotus-devnet:latest

            - name: Test
              env:
                  NETWORK_RPC_URL: ${{vars.NETWORK_RPC_URL}}
                  BLOCK_PERIOD: ${{vars.BLOCK_PERIOD}}
              run: |
                  docker exec localnet cat /root/contract >> ./contract
                  docker exec localnet cat /root/env >> ./env
                  source ./contract
                  source ./env
                  export DATASWAP_GOVERNANCE=0x09C6DEE9DB5e7dF2b18283c0CFCf714fEDB692d7
                  export DATASWAP_BIDDER=0xca942f0fd39185d971d1d58E151645e596FC7Eff
                  export DATASWAP_DATASETAUDITOR=0x405741492033D32Eb3f1F12AA1aBa40E47a59234
                  export DATASWAP_PROOFSUBMITTER=0x3D08114dD4F65B5DDCc760884249D9d1AE435Dee
                  export DATASWAP_METADATASUBMITTER=0x15B2896f76Cee4E2C567e7bC671bB701D7339B30
                  export
                  npm install
                  npm run build
                  npm run test
